---
- name: Get Token from Service Account
  ansible.builtin.uri:
    url: "{{ sso_endpoint }}"
    method: POST
    body:
      grant_type: client_credentials
      client_id: "{{ insights_auth_user }}"
      client_secret: "{{ insights_auth_password }}"
      scope: openid api.iam.service_accounts
    body_format: form-urlencoded
    status_code: 200
  register: refresh_token
